style(Interactive message): :art: A better way to display interactive…
iKonoTelecomunicaciones/whatsapp-cloud pull request #40
Opened 2024-06-13 19:16 UTC by jcardenas3

… messages

2024-06-14 21:41 UTC, dbedoya commented on whatsapp/interactive_message.py
> +        intereactive_message = InteractiveMessage(config=config)
Cambiar `intereactive_message`

2024-06-14 21:47 UTC, dbedoya commented on whatsapp_matrix/db/upgrade.py
> +        """ALTER TABLE message ADD CONSTRAINT FK_message_portal_phone_id_business_id
Hay que eliminar también la llave foŕanea `FK_message_portal_phone_id` de la tabla `message`

2024-06-17 19:19 UTC, egalvis39 requested changes

2024-06-18 19:07 UTC, dbedoya commented on whatsapp_matrix/portal.py
> +    by_app_and_phone_id: Dict[WhatsappPhone, "Portal"] = {}
Cambiar tipado de la llave del diccionario

2024-06-18 19:07 UTC, dbedoya commented on whatsapp/interactive_message.py
> +            message: str = self.config["bridge.interactive_messages.button_message"] or ""
Pasar el mensaje como parámetro para no tener que agregar el config como variable de clase (lo cual genera error al serializar)

2024-06-21 16:42 UTC, dbedoya commented on whatsapp/interactive_message.py
> +            message: str = button_item_format or ""
Dejar la variable `message` por fuera del for porque no depende de él

2024-06-21 16:44 UTC, dbedoya commented on whatsapp/interactive_message.py
> +                message: str = list_item_format or ""
Dejar la variable `message` por fuera del `for` porque no depende de él

2024-06-21 18:56 UTC, dbedoya approved these changes

2024-06-21 18:57 UTC, egalvis39 approved these changes

2024-06-21 18:57 UTC, merged